{
  "formatVersion": "1.1",
  "component": {
    "group": "com.useunloq",
    "module": "unloq-offers-core",
    "version": "1.0.0"
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "available-at": {
        "group": "com.useunloq",
        "module": "unloq-offers-core",
        "version": "1.0.0"
      }
    },
    {
      "name": "androidReleaseApiElements",
      "available-at": {
        "group": "com.useunloq",
        "module": "unloq-offers-core-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements",
      "available-at": {
        "group": "com.useunloq",
        "module": "unloq-offers-core-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements",
      "available-at": {
        "group": "com.useunloq",
        "module": "unloq-offers-core-iossimulatorarm64",
        "version": "1.0.0"
      }
    }
  ]
}

